version: 0.2
    
# env:
#   variables:
#     LIQUIBASE_COMMAND_REFERENCE_URL: offline:postgresql?snapshot=${CODEBUILD_SRC_DIR_S3syngentademo}/snapshot-dev.json

  # secrets-manager:
  #   LIQUIBASE_COMMAND_USERNAME: SYNGENTA_DEMO2:USERNAME
  #   LIQUIBASE_COMMAND_PASSWORD: SYNGENTA_DEMO2:PASSWORD
  #   LIQUIBASE_PRO_LICENSE_KEY: SYNGENTA_DEMO2:LIQUIBASE_PRO_KEY

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - liquibase --version
      - echo CODEBUILD_SRC_DIR_S3syngentademo=$CODEBUILD_SRC_DIR_S3syngentademo
  build:
    commands:
      - echo ====== Build started ======
      # - liquibase --defaultsFile=liquibase.properties checks run
      - liquibase --defaultsFile=liquibase.properties status --verbose
      - pwd
      - ls -alh
      - ls $CODEBUILD_SRC_DIR_S3syngentademo
      # - liquibase --defaultsFile=liquibase.properties history
      
  post_build:
    commands:
      - echo ====== Starting Liquibase Diff ======
      - export LIQUIBASE_COMMAND_REFERENCE_URL=offline:postgresql?snapshot=${CODEBUILD_SRC_DIR_S3syngentademo}/snapshot-dev.json
      - echo LIQUIBASE_COMMAND_REFERENCE_URL=$LIQUIBASE_COMMAND_REFERENCE_URL

      - liquibase --defaultsFile=liquibase.properties diff
      - echo ====== Build completed ======
# artifacts:
#   files:
#     - diff-dev.txt

