version: 0.2
    
# env:
  # LIQUIBASE_COMMAND_USERNAME: postgres
  # LIQUIBASE_COMMAND_PASSWORD: postgres
  # LIQUIBASE_PRO_LICENSE_KEY: ABwwGgQUjxKd8KQ1fa7HHI4P0Qsq3L22wOICAgQAjkB2jF6k42cSkAOMPPHgsp+e269W6eQeasbDCM6ks26gap8UcqOJnnGmC1REO0wyJmeH6kEg9RXXdsOLpwP0ieB0m+L0qX5V312gnWEs2srdn4y2MQa00f7rkvlIGFIITA5PytTg8VOaelFuwgOG3hl9qxIG3FPFLcvWd6LZvqt4+tSil8FJ6a8kfWPyrxG73ELEtWgGuIlH7+u9DKyMMWCGELuM3+YcHNDgfac3lri30+Dz0qB2xjm5VG5ikiiG/Hikvcbm4k/mJZEDimSRR7uMjLs/MFkcRqCCmhLUareSb2TWsfrOXaZbZ/1vNjbC5Mw3P6i4jxzzSDbVUMtQ8bZiPJsmF9QzOc180sytVZI1HkBTPUVx2GVmzCHYevTY7WSenIvzHGwv6KBspZL8ZHxRSU+2foW3y1aYmEDxRaxqUKplhidWE69InLidVKVbDN2XHpSsNZVOICoY5ggBN6HL6AazokZZr/ut35oVqvwBocsbVFDmh7l4OxlUHnQjxunywLL8leZztcOA9ZDVEGWzK+0KIUmMNYc3WRJYutMFgU10oGXpNA4PWjhlzNUzbOt2roNejsmqpY5n9S9aYQ0xzsevYnvx05tYF4E/blOhE41YWfEQKZnqXRj0MDVO7p1r+SCfCL/OvejvvcuHidU4zP0DwiY3gFZHTnNAjXk=
  # LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres-db1.cz1j1vh9uvuo.us-east-1.rds.amazonaws.com:5432/postgres
  # secrets-manager:
  #   LIQUIBASE_COMMAND_USERNAME: SYNGENTA_DEMO2:USERNAME
  #   LIQUIBASE_COMMAND_PASSWORD: SYNGENTA_DEMO2:PASSWORD
  #   LIQUIBASE_PRO_LICENSE_KEY: SYNGENTA_DEMO2:LIQUIBASE_PRO_KEY

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - liquibase --version
  build:
    commands:
      - echo ====== Build started on `date` ======
      # - liquibase --defaultsFile=liquibase.properties checks run
      # - liquibase --defaultsFile=liquibase.properties validate
      # - liquibase --defaultsFile=liquibase.properties tag codebuild-$CODEBUILD_BUILD_NUMBER
      - liquibase --defaultsFile=liquibase.properties status --verbose
      # - liquibase --defaultsFile=liquibase.properties updateSql
      - liquibase --defaultsFile=liquibase.properties update
      # - liquibase --defaultsFile=liquibase.properties history
      
  post_build:
    commands:
      - echo ====== Starting Liquibase Snapshot ======
      - liquibase --defaultsFile=liquibase.properties --outputFile=snapshot-dev.json snapshot --snapshotFormat=json
      - echo ====== Build completed on `date` ======
# artifacts:
#   files:
    - snapshot-dev.json

